In [2]:
import os
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [3]:
# Load environment variables from .env file
load_dotenv()

# Access the variables 
psql_username = os.getenv('PSQL_USERNAME')
psql_password = os.getenv('PSQL_PASSWORD')
psql_host = os.getenv('PSQL_HOST')
psql_port = os.getenv('PSQL_PORT')
db_name = os.getenv('CONTROL_DB_NAME')

# Define the database url
db_url = f"postgresql://{psql_username}:{psql_password}@{psql_host}:{psql_port}/{db_name}" 

# Create the engine object
engine = create_engine(db_url)

# Write ethe SQL query
query = 'SELECT * FROM trades'

# Read the SQL query into a DataFrame
control_df = pd.read_sql(query, engine)

# Show the DataFrame's head
control_df

,trade_count,current_datetime,currency,volume,buy_exchange,buy_price,total_purchase_amount,sell_exchange,sell_price,total_sale_amount,profit,spread_percentage,wallet_balance
0,1,2024-02-25T19:16:40.747701,ethereum,1.0,Bitstamp,3108.90000,3108.90000,Gemini,3108.97000,3108.97000,0.07000,0.002252,0.07000
1,2,2024-02-25T19:17:18.572780,bitcoin,1.0,Kraken,51644.30000,51644.30000,Poloniex,51647.87000,51647.87000,3.57000,0.006913,3.64000
2,3,2024-02-25T19:17:18.572780,ethereum,1.0,Bitstamp,3109.80000,3109.80000,Gemini,3109.82000,3109.82000,0.02000,0.000643,3.66000
3,4,2024-02-25T19:17:56.480435,bitcoin,1.0,Kraken,51685.90000,51685.90000,Poloniex,51689.58000,51689.58000,3.68000,0.007120,7.34000
4,5,2024-02-25T19:17:56.480435,solana,1.0,Bitstamp,103.30780,103.30780,Kraken,103.31000,103.31000,0.00220,0.002130,7.34220
5,6,2024-02-25T19:18:32.684129,bitcoin,1.0,Binance,51744.52000,51744.52000,Bitstamp,51747.00000,51747.00000,2.48000,0.004793,9.82220
6,7,2024-02-25T19:18:32.684129,bitcoin,1.0,Binance,51744.52000,51744.52000,Gemini,51749.00000,51749.00000,4.48000,0.008658,14.30220
7,8,2024-02-25T19:18:32.684129,bitcoin,1.0,Binance,51744.52000,51744.52000,Kraken,51756.90000,51756.90000,12.38000,0.023925,26.68220
8,9,2024-02-25T19:18:32.684129,bitcoin,1.0,Bitstamp,51753.00000,51753.00000,Kraken,51756.90000,51756.90000,3.90000,0.007536,30.58220
9,10,2024-02-25T19:18:32.684129,bitcoin,1.0,Gemini,51754.54000,51754.54000,Kraken,51756.90000,51756.90000,2.36000,0.004560,32.94220
10,11,2024-02-25T19:18:32.684129,ethereum,1.0,Binance,3117.84000,3117.84000,Kraken,3118.19000,3118.19000,0.35000,0.011226,33.29220
11,12,2024-02-25T19:18:32.684129,ethereum,1.0,Bitstamp,3118.10000,3118.10000,Kraken,3118.19000,3118.19000,0.09000,0.002886,33.38220
12,13,2024-02-25T19:18:32.684129,ethereum,1.0,Gemini,3117.44000,3117.44000,Kraken,3118.19000,3118.19000,0.75000,0.024058,34.13220
13,14,2024-02-25T19:19:08.500334,bitcoin,1.0,Binance,51755.39000,51755.39000,Gemini,51757.81000,51757.81000,2.42000,0.004676,36.55220
14,15,2024-02-25T19:19:08.500334,bitcoin,1.0,Binance,51755.39000,51755.39000,Kraken,51760.70000,51760.70000,5.31000,0.010260,41.86220
15,16,2024-02-25T19:19:08.500334,bitcoin,1.0,Bitstamp,51754.00000,51754.00000,Gemini,51757.81000,51757.81000,3.81000,0.007362,45.67220
16,17,2024-02-25T19:19:08.500334,bitcoin,1.0,Bitstamp,51754.00000,51754.00000,Kraken,51760.70000,51760.70000,6.70000,0.012946,52.37220
17,18,2024-02-25T19:19:08.500334,ethereum,1.0,Binance,3118.97000,3118.97000,Poloniex,3119.02000,3119.02000,0.05000,0.001603,52.42220
18,19,2024-02-25T19:19:08.500334,ethereum,1.0,Bitstamp,3118.80000,3118.80000,Poloniex,3119.02000,3119.02000,0.22000,0.007054,52.64220
19,20,2024-02-25T19:19:08.500334,ethereum,1.0,Gemini,3117.70000,3117.70000,Kraken,3118.71000,3118.71000,1.01000,0.032396,53.65220
20,21,2024-02-25T19:19:08.500334,ethereum,1.0,Gemini,3117.70000,3117.70000,Poloniex,3119.02000,3119.02000,1.32000,0.042339,54.97220
21,22,2024-02-25T19:19:08.500334,solana,1.0,Bitstamp,103.57630,103.57630,Gemini,103.57700,103.57700,0.00070,0.000676,54.97290
22,23,2024-02-25T19:19:08.500334,solana,1.0,Bitstamp,103.57630,103.57630,Kraken,103.59000,103.59000,0.01370,0.013227,54.98660
23,24,2024-02-25T19:19:43.470451,bitcoin,1.0,Bitstamp,51699.00000,51699.00000,Kraken,51702.10000,51702.10000,3.10000,0.005996,58.08660
24,25,2024-02-25T19:19:43.470451,bitcoin,1.0,Bitstamp,51699.00000,51699.00000,Poloniex,51702.22000,51702.22000,3.22000,0.006228,61.30660
25,26,2024-02-25T19:19:43.470451,bitcoin,1.0,Gemini,51694.27000,51694.27000,Kraken,51702.10000,51702.10000,7.83000,0.015147,69.13660
26,27,2024-02-25T19:19:43.470451,bitcoin,1.0,Gemini,51694.27000,51694.27000,Poloniex,51702.22000,51702.22000,7.95000,0.015379,77.08660
27,28,2024-02-25T19:19:43.470451,ethereum,1.0,Gemini,3114.89000,3114.89000,Kraken,3115.59000,3115.59000,0.70000,0.022473,77.78660
28,29,2024-02-25T19:19:43.470451,polygon,1.0,Binance,0.99040,0.99040,Poloniex,0.99140,0.99140,0.00100,0.100969,77.78760
29,30,2024-02-25T19:19:43.470451,polygon,1.0,Bitstamp,0.99032,0.99032,Poloniex,0.99140,0.99140,0.00108,0.109056,77.78868
30,31,2024-02-25T19:19:43.470451,polygon,1.0,Gemini,0.99116,0.99116,Poloniex,0.99140,0.99140,0.00024,0.024214,77.78892
31,32,2024-02-25T19:19:43.470451,polygon,1.0,Kraken,0.99070,0.99070,Poloniex,0.99140,0.99140,0.00070,0.070657,77.78962
32,33,2024-02-25T19:19:43.470451,xrp,1.0,Bitstamp,0.54187,0.54187,Gemini,0.54201,0.54201,0.00014,0.025836,77.78976

In [4]:
control_df['current_datetime'] = pd.to_datetime(control_df['current_datetime'])
control_df['current_datetime'] = pd.to_datetime(control_df['current_datetime'].dt.date)

control_df.set_index('current_datetime')
display(control_df.groupby(['currency', 'buy_exchange'])[['total_purchase_amount','profit', 'spread_percentage', 'wallet_balance']].mean())
display(control_df.groupby(['currency'])[['total_purchase_amount','profit', 'spread_percentage', 'wallet_balance']].mean())

                       total_purchase_amount    profit  spread_percentage  \
currency buy_exchange
bitcoin  Binance                 51748.86800  5.414000           0.010462
         Bitstamp                51731.80000  4.146000           0.008014
         Gemini                  51714.36000  6.046667           0.011695
         Kraken                  51665.10000  3.625000           0.007016
ethereum Binance                  3118.40500  0.200000           0.006414
         Bitstamp                 3113.90000  0.100000           0.003209
         Gemini                   3116.93250  0.945000           0.030316
polygon  Binance                     0.99040  0.001000           0.100969
         Bitstamp                    0.99032  0.001080           0.109056
         Gemini                      0.99116  0.000240           0.024214
         Kraken                      0.99070  0.000700           0.070657
solana   Bitstamp                  103.48680  0.005533           0.005344
xrp      Bitstamp                    0.54187  0.000140           0.025836

                       wallet_balance
currency buy_exchange
bitcoin  Binance            25.844200
         Bitstamp           49.603960
         Gemini             59.721800
         Kraken              5.490000
ethereum Binance            42.857200
         Bitstamp           22.438600
         Gemini             55.135800
polygon  Binance            77.787600
         Bitstamp           77.788680
         Gemini             77.788920
         Kraken             77.789620
solana   Bitstamp           39.100567
xrp      Bitstamp           77.789760

          total_purchase_amount    profit  spread_percentage  wallet_balance
currency
bitcoin            51725.108000  4.879333           0.009433       37.825747
ethereum            3116.014000  0.458000           0.014693       39.601200
polygon                0.990645  0.000755           0.076224       77.788705
solana               103.486800  0.005533           0.005344       39.100567
xrp                    0.541870  0.000140           0.025836       77.789760

In [ ]:
.13153